/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _dsh_command_approval_view_commandExplainer_explain_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _dsh_command_approval_view_commandExplainer_explain_parameter_1$schema = z.string()
const _dsh_command_approval_view_commandExplainer_explain_result$schema = z.object({
  summary: z.string(),
  fallback: z.string(),
  diagnostic: z.string().optional(),
})

export const TYPERT = {
  package: 'dsh-command-approval-view',
  face: 'host',
  schemas: [],
  invocations: [
    {
      id: 'dsh-command-approval-view#commandExplainer/explain',
      service: 'commandExplainer',
      namespace: 'commandExplainer',
      method: 'explain',
      implementation: 'remoteExportExplain',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _dsh_command_approval_view_commandExplainer_explain_parameter_0$schema,
          },
        },
        {
          name: 'command',
          wire: 'command',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-command-approval-view#commandExplainer/explain:command',
            schema: _dsh_command_approval_view_commandExplainer_explain_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-command-approval-view#commandExplainer/explain:result',
        schema: _dsh_command_approval_view_commandExplainer_explain_result$schema,
      },
      sourceLocation: { file: 'src/host/index.ts', line: 1, column: 1 },
    },
  ],
  model: {
    services: [
      {
        description: 'Model-backed explainer for pending shell commands shown in approval prompts.',
        summary: 'explain(command) returns a neutral whole-command explanation: model first, deterministic lexicon fallback.',
        tags: [],
        jsDoc: '/** Explains a pending shell command for the approval panel. */',
        key: 'commandExplainer',
        exportName: 'CommandExplainerService',
        members: [
          {
            kind: 'method',
            name: 'remoteExportExplain',
            signature: 'remoteExportExplain(agent: AgentLike, command: string): Promise<ExplainResult>',
            summary: 'Return a neutral whole-command explanation.',
            jsDoc: '/** Remote face: explain(command). */',
          },
        ],
        types: [
          { name: 'AgentLike', declaration: 'export interface AgentLike { session?: { id?: string } }' },
          { name: 'ExplainResult', declaration: 'export interface ExplainResult { summary: string; fallback: string; diagnostic?: string }' },
        ],
      },
    ],
    events: [],
    objects: [],
  },
}
